project:
  type: website
  output-dir: docs
  
execute:
  python: "env/Scripts/python.exe"

website:
  title: "Consultoría Bioestadística"
  favicon: img/mcdlogo.png
  image: img/mcdlogo.png
  repo-url: https://github.com/Jenn-LG/Bioestadistica
  repo-actions: [issue, source]
  open-graph: true
  twitter-card: true
  page-navigation: true
#  back-to-top-navigation: true
  page-footer:
    border: true
    left: | 
      Powered by [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/).
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Introducción
      - about.qmd
      - inicial.qmd
      - anova.qmd
      - regresion.qmd
#      - Stats_Project.ipynb
      - href: frecuencia.qmd
        text: "Análisis de frecuencia y espectral"
      - conclusiones.qmd  

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    lang: es

editor: visual

